### ISSUE TITLE
Links don't open in browser

### ISSUE THREAD

**Issue by makew0rld** [flathub/md.obsidian.Obsidian#152] opened 2023-05-15 13:38 UTC
### Description

After updating to the newest Obsidian, links no longer open in my browser. This does not happen with the latest Obisidian AppImage.

### System Information

```bash session
Arch Linux
XFCE
Flatpak 1.15.4
Obsidian 1.2.8, commit 1e288c649c0306a0aff1f382471b6cc002c8c643f8bf75547475707a65f72fb5
Firefox 113.0.1
```

### Sandbox Permissions

```bash session
[Context]
shared=network;ipc;
sockets=x11;wayland;pulseaudio;ssh-auth;
devices=dri;
filesystems=home;/media;~/Software;/mnt;/run/media;xdg-run/app/com.discordapp.Discord:create;
persistent=~/.ssh;

[Session Bus Policy]
org.freedesktop.portal.Fcitx=talk

[Environment]
OBSIDIAN_DISABLE_GPU_SANDBOX=0
SSH_ASKPASS=/app/libexec/openssh/ssh-askpass
OBSIDIAN_USE_WAYLAND=0
OBSIDIAN_ENABLE_AUTOSCROLL=0
PATH=/usr/bin:/app/bin:/app/texlive/bin:/app/texlive/bin/x86_64-linux:/app/texlive/bin/aarch64-linux
OBSIDIAN_DISABLE_GPU=0
```

### Logs

```bash session
Debug: Will run Obsidian with the following arguments: 
Debug: Additionally, user gave: 
[13:0515/093716.543787:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
2023-05-15 13:37:16 Loading main app package /app/resources/obsidian.asar
Updates disabled.
LaunchProcess: failed to execvp:
xdg-settings

(obsidian:13): Gtk-WARNING **: 09:37:16.747: Theme parsing error: gtk.css:68:35: The style property GtkButton:child-displacement-x is deprecated and shouldn't be used anymore. It will be removed in a future version

(obsidian:13): Gtk-WARNING **: 09:37:16.747: Theme parsing error: gtk.css:69:35: The style property GtkButton:child-displacement-y is deprecated and shouldn't be used anymore. It will be removed in a future version

(obsidian:13): Gtk-WARNING **: 09:37:16.747: Theme parsing error: gtk.css:73:46: The style property GtkScrolledWindow:scrollbars-within-bevel is deprecated and shouldn't be used anymore. It will be removed in a future version
[13:0515/093716.809716:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[13:0515/093716.809770:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[13:0515/093717.825039:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.StartServiceByName: object_path= /org/freedesktop/DBus: org.freedesktop.DBus.Error.NoReply: Did not receive a reply. Possible causes include: the remote application did not send a reply, the message bus security policy blocked the reply, the reply timeout expired, or the network connection was broken.
Opening URL: https://svelte.dev/tutorial/multiple-select-bindings
Failed to call portal: GDBus.Error:org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.freedesktop.portal.Desktop': timed out (service_start_timeout=120000ms)
Failed to call portal: GDBus.Error:org.freedesktop.DBus.Error.TimedOut: Failed to activate service 'org.freedesktop.portal.Desktop': timed out (service_start_timeout=120000ms)
```

**Comment by joshua-stone** [comment] 2023-05-15 18:17
This appears to be a bug in xdg-portal-desktop(-gnome):

https://github.com/archlinux/svntogit-packages/commit/0d987faf7b25400495917dd368ae924204d3f984

@heftig would you happen to have more information on this?

**Comment by heftig** [comment] 2023-05-15 19:53
You mean [the backported commit](https://github.com/flatpak/xdg-desktop-portal/commit/2a219279997c2124c8a639b0d009c9946ec97b40) introduced this bug? Is the previous package release affected? Is the [`xdg-desktop-portal-1.16` branch](https://github.com/flatpak/xdg-desktop-portal/commits/xdg-desktop-portal-1.16) also affected? If they're not, we'll need to backport more. Otherwise this is probably an upstream bug.

**Comment by makew0rld** [comment] 2023-05-16 13:24
- Flatpak 1.15.4 (`1:1.15.4-1` in Arch)
- Obsidian 1.2.8, commit 1e288c649c0306a0aff1f382471b6cc002c8c643f8bf75547475707a65f72fb5
- xdg-desktop-portal 1.16.0-3
- xdg-desktop-portal-gnome 44.1-2
- xdg-desktop-portal-gtk 1.14.1-1
- xdg-desktop-portal-kde 5.27.5-1

Any other software?

**Comment by heftig** [comment] 2023-05-16 13:34
Was it an upgrade of xdg-desktop-portal-gnome from 43 to 44 that triggered this?

**Comment by makew0rld** [comment] 2023-05-16 14:14
I'm not sure, I upgraded my system all at once (flatpak and Arch pkgs) so I wasn't able to isolate the problem to a specific package.

**Comment by joshua-stone** [comment] 2023-05-16 14:37
Is there a way to roll back an update? Immutable/image-based distros like Silverblue have mechanisms for rolling back in the event of a regression, but hopefully pacman has some facilities for this so we can effectively pinpoint which packages are impacted.

**Comment by Erick555** [comment] 2023-05-16 16:54
try removing xdg-desktop-portal-gnome from the system and reboot or restart desktop session.

**Comment by makew0rld** [comment] 2023-05-16 19:16
I uninstalled `xdg-desktop-portal-gnome` and `xdg-desktop-portal-kde`, so my only xdg-desktop-portal implementation is now `xdg-desktop-portal-gtk`. Not sure why I had those other ones. Without needing to restart anything except Obisidan, links are now opening again.

I'll leave it to the maintainers to close this issue in case it should stay open.

**Comment by joshua-stone** [comment] 2023-05-17 13:55
Marking as resolved since it doesn't seem intrinsic to Obsidian flatpak. This is still useful information for any future bug reports though.

Thank you!

**Closed by joshua-stone** 2023-05-17 13:55 UTC
Labels: bug
