### ISSUE TITLE
No App icon when downloading from flatpak

### ISSUE THREAD

**Issue by jongeorge1999** [flathub/md.obsidian.Obsidian#348] opened 2024-08-09 11:29 UTC
### Description

Using Fedora 40 with KDE 6. When downloading the flatpak it does not have an app icon an appears as the default blank page icon.

### Obsidian Version

```bash session
Obsidian - Markdown-based knowledge base

          ID: md.obsidian.Obsidian
         Ref: app/md.obsidian.Obsidian/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.6.7
     License: LicenseRef-proprietary=https://obsidian.md/eula
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 627.9 MB
     Runtime: org.freedesktop.Platform/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

      Commit: e2f84d233eb9c7908b175f661cdbb0186b3ed3c50fed23e8692951e4816ffd67
      Parent: 4e1c2f1197885a15dc944b1e0f53663301e16a9ccc09dd5f8b5219aa2fdef45a
     Subject: Add info about broken pen tablet support on Wayland (#347) (547fc3ab)
        Date: 2024-08-06 01:49:19 +0000
```

### Sandbox Permissions

```bash session
[Context]
shared=network;ipc;
sockets=x11;pulseaudio;ssh-auth;
devices=dri;
filesystems=home;/media;xdg-run/gnupg:ro;/mnt;/run/media;~/.local/share/fonts:ro;xdg-run/app/com.discordapp.Discord:create;
persistent=~/.ssh;

[Environment]
SSH_ASKPASS=/app/libexec/openssh/ssh-askpass
OBSIDIAN_CLEAN_CACHE=1
OBSIDIAN_ENABLE_AUTOSCROLL=0
PATH=/usr/bin:/app/bin:/app/texlive/bin:/app/texlive/bin/x86_64-linux:/app/texlive/bin/aarch64-linux
XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons:~/.icons
OBSIDIAN_DISABLE_GPU=0
GH_PATH=gh
```

### Hardware Information

```bash session
[1] 19496
name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: AMD (0x1002)
    Device: AMD Radeon 780M (radeonsi, gfx1103_r1, LLVM 18.1.6, DRM 3.57, 6.9.12-200.fc40.x86_64) (0x15bf)
    Version: 24.1.5
    Accelerated: yes
    Video memory: 512MB
    Unified memory: no
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
Memory info (GL_ATI_meminfo):
    VBO free memory - total: 28 MB, largest block: 28 MB
    VBO free aux. memory - total: 14562 MB, largest block: 14562 MB
    Texture free memory - total: 28 MB, largest block: 28 MB
    Texture free aux. memory - total: 14562 MB, largest block: 14562 MB
    Renderbuffer free memory - total: 28 MB, largest block: 28 MB
    Renderbuffer free aux. memory - total: 14562 MB, largest block: 14562 MB
Memory info (GL_NVX_gpu_memory_info):
    Dedicated video memory: 512 MB
    Total available memory: 16205 MB
    Currently available dedicated video memory: 28 MB
OpenGL vendor string: AMD
OpenGL renderer string: AMD Radeon 780M (radeonsi, gfx1103_r1, LLVM 18.1.6, DRM 3.57, 6.9.12-200.fc40.x86_64)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 24.1.5
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.1.5
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 24.1.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### System Information

```bash session
Fedora 40 with KDE Plasma 6
```

**Comment by imahajanshubham** [comment] 2024-08-09 14:52
Similar issue happens with me on Fedora KDE spin (39/40 both) where on fresh install if I install bunch of flatpaks (all default theme/icons settings with no change), some icons would show blank white page icons.

![Screenshot_20240809_201805](https://github.com/user-attachments/assets/c5cabb3d-1008-47f0-8050-aefc838bc93c)

So for easy fix/hack, I simply go to System Settings and switch default icon theme to Breeze Dark > Hit apply then switch back to Breeze Light (or vice-versa) and it regenerates icon cache.

I cannot show Obsidian specific issue because I already did this trick during fresh install.
![Screenshot_20240809_201945](https://github.com/user-attachments/assets/603804c5-8b3d-4037-aae6-afa289615cad)

Tested on:
Fedora KDE 40 latest stable.

**Comment by joshua-stone** [comment] 2024-08-09 15:14
I have installed a Fedora [KDE VM using a recent respin ISO](https://dl.fedoraproject.org/pub/alt/live-respins/). So far I'm not able to reproduce this issue:

[Screencast from 2024-08-09 11-06-16.webm](https://github.com/user-attachments/assets/eceeb4a9-fbcd-430d-b28e-e17330fc2726)

This could be another transient issue with KDE Plasma which has been previously reported:

https://github.com/flathub/md.obsidian.Obsidian/issues/265

Please try some workarounds like restarting the system, regenerate desktop icons, or the switch themes as described by @imahajanshubham.

**Comment by joshua-stone** [comment] 2024-08-10 17:55
I'm going to close this issue since it doesn't appear to be intrinsic to the Obsidian flatpak and is a transient issue.

**Closed by joshua-stone** 2024-08-10 17:55 UTC
Labels: bug
