### ISSUE TITLE
Multiple Errors when opening the App (app still opens)

### ISSUE THREAD

**Issue by vetricodes** [flathub/md.obsidian.Obsidian#297] opened 2024-02-18 02:01 UTC
### Description

Multiple errors occur when opening the app (attached in the Logs section), however the app still opens. This doesn't happen with official appimage

### Obsidian Version

```bash session
Obsidian - Markdown-based knowledge base

          ID: md.obsidian.Obsidian
         Ref: app/md.obsidian.Obsidian/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.5.3
     License: LicenseRef-proprietary=https://obsidian.md/eula
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 604.3 MB
     Runtime: org.freedesktop.Platform/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

      Commit: 8701844fd89d910215d99921219380de4f8bd5c88debb77a836303ef8efd1ead
      Parent: 1c13b24618b78278de7af0d4a4a832d793ddb9613588f4b400ae3ad3d2985bca
     Subject: Suppress segfault output if obsidian crashes (#290) (65907367)
        Date: 2024-02-17 22:27:20 +0000
```

### Sandbox Permissions

```bash session
[Context]
shared=network;ipc;
sockets=x11;pulseaudio;ssh-auth;
devices=dri;
filesystems=home;/media;xdg-run/gnupg:ro;/mnt;/run/media;~/.local/share/fonts:ro;xdg-run/app/com.discordapp.Discord:create;
persistent=~/.ssh;

[Environment]
SSH_ASKPASS=/app/libexec/openssh/ssh-askpass
OBSIDIAN_CLEAN_CACHE=1
OBSIDIAN_ENABLE_AUTOSCROLL=0
PATH=/usr/bin:/app/bin:/app/texlive/bin:/app/texlive/bin/x86_64-linux:/app/texlive/bin/aarch64-linux
XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons:~/.icons
OBSIDIAN_DISABLE_GPU=0
GH_PATH=gh
```

### Hardware Information

```bash session
00:02.0 VGA compatible controller [0300]: Intel Corporation Skylake GT2 [HD Graphics 520] [8086:1916] (rev 07)

----------------------

name of display: :0
display: :0  screen: 0
direct rendering: Yes
Extended renderer info (GLX_MESA_query_renderer):
    Vendor: Intel (0x8086)
    Device: Mesa Intel(R) HD Graphics 520 (SKL GT2) (0x1916)
    Version: 23.3.5
    Accelerated: yes
    Video memory: 7696MB
    Unified memory: yes
    Preferred profile: core (0x1)
    Max core profile version: 4.6
    Max compat profile version: 4.6
    Max GLES1 profile version: 1.1
    Max GLES[23] profile version: 3.2
OpenGL vendor string: Intel
OpenGL renderer string: Mesa Intel(R) HD Graphics 520 (SKL GT2)
OpenGL core profile version string: 4.6 (Core Profile) Mesa 23.3.5
OpenGL core profile shading language version string: 4.60
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile

OpenGL version string: 4.6 (Compatibility Profile) Mesa 23.3.5
OpenGL shading language version string: 4.60
OpenGL context flags: (none)
OpenGL profile mask: compatibility profile

OpenGL ES profile version string: OpenGL ES 3.2 Mesa 23.3.5
OpenGL ES profile shading language version string: OpenGL ES GLSL ES 3.20
```

### System Information

```bash session
Fedora 39, Gnome,Flatpak 1.15.6, Wayland
```

### Logs

```bash session
Deleting cache directory: /home/vetri/.var/app/md.obsidian.Obsidian/config/obsidian/GPUCache
Debug: Will run Obsidian with the following arguments: 
Debug: Additionally, user gave: 
[14:0218/145552.527205:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
LaunchProcess: failed to execvp:
xdg-settings
Uncaught Exception Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:930:11)
    at Socket._write (node:net:942:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at fn (/app/resources/app.asar/main.js:57:10)
    at Object.<anonymous> (/app/resources/app.asar/main.js:445:2)
    at Module._compile (node:internal/modules/cjs/loader:1269:14) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
Uncaught Exception Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:930:11)
    at Socket._write (node:net:942:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at fn (/app/resources/app.asar/main.js:57:10)
    at Object.<anonymous> (/app/resources/app.asar/main.js:445:2)
    at Module._compile (node:internal/modules/cjs/loader:1269:14) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
A JavaScript error occurred in the main process
Uncaught Exception:
Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:930:11)
    at Socket._write (node:net:942:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at fn (/app/resources/app.asar/main.js:57:10)
    at Object.<anonymous> (/app/resources/app.asar/main.js:445:2)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
Gtk-Message: 14:55:52.776: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:55:52.777: Failed to load module "pk-gtk-module"
Gtk-Message: 14:55:52.780: Failed to load module "canberra-gtk-module"
Gtk-Message: 14:55:52.780: Failed to load module "pk-gtk-module"
[14:0218/145552.815732:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[14:0218/145552.815932:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Uncaught Exception Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:930:11)
    at Socket._write (node:net:942:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at fn (/app/resources/app.asar/main.js:57:10)
    at runUpdate (/app/resources/app.asar/main.js:151:3)
    at update (/app/resources/app.asar/main.js:139:9) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
Uncaught Exception Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:930:11)
    at Socket._write (node:net:942:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at fn (/app/resources/app.asar/main.js:57:10)
    at runUpdate (/app/resources/app.asar/main.js:151:3)
    at update (/app/resources/app.asar/main.js:139:9) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
[14:0218/145611.367659:ERROR:network_service_instance_impl.cc(558)] Network service crashed, restarting service.
Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49935)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
Uncaught Exception Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:930:11)
    at Socket._write (node:net:942:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at fn (/app/resources/app.asar/main.js:57:10)
    at runUpdate (/app/resources/app.asar/main.js:155:3)
    at async update (/app/resources/app.asar/main.js:139:3) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
Uncaught Exception Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:930:11)
    at Socket._write (node:net:942:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at fn (/app/resources/app.asar/main.js:57:10)
    at runUpdate (/app/resources/app.asar/main.js:155:3)
    at async update (/app/resources/app.asar/main.js:139:3) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
Error: net::ERR_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:2:49935)
    at SimpleURLLoaderWrapper.emit (node:events:513:28)
Uncaught Exception Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:930:11)
    at Socket._write (node:net:942:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at fn (/app/resources/app.asar/main.js:57:10)
    at runUpdate (/app/resources/app.asar/main.js:176:3)
    at async update (/app/resources/app.asar/main.js:139:3) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
Uncaught Exception Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:930:11)
    at Socket._write (node:net:942:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at fn (/app/resources/app.asar/main.js:57:10)
    at runUpdate (/app/resources/app.asar/main.js:176:3)
    at async update (/app/resources/app.asar/main.js:139:3) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
```

**Comment by coritanic** [comment] 2024-02-18 02:36
This also happens to me on NixOS GNOME. The issue started since the commit 659073670252e083bf5b97120ab00d5a8bc3acf2.

The problem doesn't exist in the previous version: `sudo flatpak update md.obsidian.Obsidian --commit=1c13b24618b78278de7af0d4a4a832d793ddb9613588f4b400ae3ad3d2985bca` (d654005689c38af1321f97f26b4bde9039d6b8e2).

The issue is reproducible on a fresh Fedora VM.

**Comment by npomphrey** [comment] 2024-02-18 09:30
Same here.
Working fine yesterday;  2024.02.17
Fedora 39 - Gnome desktop 
Once you've closed the multiple error pop-ups, Obsidian opens and appears to function correctly.
I raised this on Obsidian.org and others are also having the same problem (Linux Flatpak)

Uncaught Exception:
Error: write EPIPE
atafterWriteDispatched (nodeinternal/stream_base_commons:160:15)
atwriteGeneric (nodeinternal/stream_base_commons:151:3)
at Socket,_writeGeneric (node:net:930:11)
at Socket,_write (node:net:942:8)
atwriteOrBuffer (nodecinternal/streams/writable:392:12)
at_write (nodeinternal/streams/writable:333:10)
atWritable.write (nodeinternal/streams/writable:337:10)
atfn (/app/resources/app.asar/mainjs:57:10)
atrunUpdate (/app/resources/app.asar/main.js:151:
at update (fapp/resources/app.asar/main.js:139:9)

Ok

**Comment by merrkry** [comment] 2024-02-18 09:34
Same here, happens on KDE + Arch Linux
![图片](https://github.com/flathub/md.obsidian.Obsidian/assets/124278440/dd0ce42e-343c-4b61-af6b-6c02cf8f662b)
It seems to happen when checking for updates / clicking at an external link.

**Comment by rxptor** [comment] 2024-02-18 13:05
> This also happens to me on NixOS GNOME. The issue started since the commit [6590736](https://github.com/flathub/md.obsidian.Obsidian/commit/659073670252e083bf5b97120ab00d5a8bc3acf2).
> 
> The problem doesn't exist in the previous version: `sudo flatpak update md.obsidian.Obsidian --commit=1c13b24618b78278de7af0d4a4a832d793ddb9613588f4b400ae3ad3d2985bca` ([d654005](https://github.com/flathub/md.obsidian.Obsidian/commit/d654005689c38af1321f97f26b4bde9039d6b8e2)).
> 
> The issue is reproducible on a fresh Fedora VM.
> 
>  Kooha-2024-02-18-05-42-21.mp4

Same issue. Thanks for "hot fix".

**Comment by Onxr** [comment] 2024-02-18 13:31
> This also happens to me on NixOS GNOME. The issue started since the commit [6590736](https://github.com/flathub/md.obsidian.Obsidian/commit/659073670252e083bf5b97120ab00d5a8bc3acf2).
> 
> The problem doesn't exist in the previous version: `sudo flatpak update md.obsidian.Obsidian --commit=1c13b24618b78278de7af0d4a4a832d793ddb9613588f4b400ae3ad3d2985bca` ([d654005](https://github.com/flathub/md.obsidian.Obsidian/commit/d654005689c38af1321f97f26b4bde9039d6b8e2)).
> 
> The issue is reproducible on a fresh Fedora VM.
> 
>  Kooha-2024-02-18-05-42-21.mp4

Thanks it works for now but if I update I get this

```
flatpak run md.obsidian.Obsidian 
Deleting cache directory: /home/aceiow/.var/app/md.obsidian.Obsidian/config/obsidian/GPUCache
Debug: Will run Obsidian with the following arguments: 
Debug: Additionally, user gave: 
[14:0218/191146.457526:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
LaunchProcess: failed to execvp:
xdg-settings
Uncaught Exception Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:930:11)
    at Socket._write (node:net:942:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at fn (/app/resources/app.asar/main.js:57:10)
    at Object.<anonymous> (/app/resources/app.asar/main.js:445:2)
    at Module._compile (node:internal/modules/cjs/loader:1269:14) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
Uncaught Exception Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:930:11)
    at Socket._write (node:net:942:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at fn (/app/resources/app.asar/main.js:57:10)
    at Object.<anonymous> (/app/resources/app.asar/main.js:445:2)
    at Module._compile (node:internal/modules/cjs/loader:1269:14) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
A JavaScript error occurred in the main process
Uncaught Exception:
Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:930:11)
    at Socket._write (node:net:942:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at fn (/app/resources/app.asar/main.js:57:10)
    at Object.<anonymous> (/app/resources/app.asar/main.js:445:2)
    at Module._compile (node:internal/modules/cjs/loader:1269:14)
[14:0218/191146.569989:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[14:0218/191146.570026:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
Uncaught Exception Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:930:11)
    at Socket._write (node:net:942:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at fn (/app/resources/app.asar/main.js:57:10)
    at runUpdate (/app/resources/app.asar/main.js:151:3)
    at update (/app/resources/app.asar/main.js:139:9) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
Uncaught Exception Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:930:11)
    at Socket._write (node:net:942:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at fn (/app/resources/app.asar/main.js:57:10)
    at runUpdate (/app/resources/app.asar/main.js:151:3)
    at update (/app/resources/app.asar/main.js:139:9) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
Uncaught Exception Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:930:11)
    at Socket._write (node:net:942:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at fn (/app/resources/app.asar/main.js:57:10)
    at runUpdate (/app/resources/app.asar/main.js:153:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}
Uncaught Exception Error: write EPIPE
    at afterWriteDispatched (node:internal/stream_base_commons:160:15)
    at writeGeneric (node:internal/stream_base_commons:151:3)
    at Socket._writeGeneric (node:net:930:11)
    at Socket._write (node:net:942:8)
    at writeOrBuffer (node:internal/streams/writable:392:12)
    at _write (node:internal/streams/writable:333:10)
    at Writable.write (node:internal/streams/writable:337:10)
    at fn (/app/resources/app.asar/main.js:57:10)
    at runUpdate (/app/resources/app.asar/main.js:153:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -32,
  code: 'EPIPE',
  syscall: 'write'
}

```

**Comment by zactionn** [comment] 2024-02-18 14:55
Having the same issue here too. Fedora39 fresh install after dnf updates.

> Same here, happens on KDE + Arch Linux ![图片](https://private-user-images.githubusercontent.com/124278440/305702863-dd0ce42e-343c-4b61-af6b-6c02cf8f662b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgyNjgyOTksIm5iZiI6MTcwODI2Nzk5OSwicGF0aCI6Ii8xMjQyNzg0NDAvMzA1NzAyODYzLWRkMGNlNDJlLTM0M2MtNGI2MS1hZjZiLTZjMDJjZjhmNjYyYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxOFQxNDUzMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zODA2NTQ4MDUzYjQ5ZTA2MjU4MTA3ZGEwZGM1ZDA1NGM0ZWYyMjY5NDVjNWVlNjRkZWYwZWQxZTM5NWYyMGQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.vsJe5-tseWbsu8SX1bBaIS6dSSdwx2HlgzIG_4lUMCQ) It seems to happen when checking for updates / clicking at an external link.

**Comment by IronLllama** [comment] 2024-02-18 14:57
Same on mint / Cinnamon, again since the update. 

![image](https://github.com/flathub/md.obsidian.Obsidian/assets/4867637/4ad847d1-98c8-4d2d-aed3-b435cc1df54a)

**Comment by joshua-stone** [comment] 2024-02-18 15:21
I'm going to revert my latest commit due to it being linked in this issue:

https://github.com/flathub/md.obsidian.Obsidian/pull/298

**Comment by joshua-stone** [comment] 2024-02-18 17:06
@vetricodes @coritanic @Onxr @rxptor @zactionn @powerarmorpatch It should be reverted now:

```
$ flatpak remote-info --log flathub md.obsidian.Obsidian

Obsidian - Markdown-based knowledge base

        ID: md.obsidian.Obsidian
       Ref: app/md.obsidian.Obsidian/x86_64/stable
      Arch: x86_64
    Branch: stable
   Version: 1.5.3
   License: LicenseRef-proprietary=https://obsidian.md/eula
Collection: org.flathub.Stable
  Download: 184.7 MB
 Installed: 604.3 MB
   Runtime: org.freedesktop.Platform/x86_64/23.08
       Sdk: org.freedesktop.Sdk/x86_64/23.08

    Commit: 26c9563c28b3250935a00151e4efcb6b4a8488a6b1066b111cf943d882effca7
    Parent: 7f22efbe5483919dffe60d2b67c436adb33e217a1c35792a1f43ab781c70c358
   Subject: Revert "Suppress segfault output if obsidian crashes (#290)" (e817cda1)
      Date: 2024-02-18 16:53:39 +0000
   History: 
```

Please update Obsidian:

```
$ flatpak update md.obsidian.Obsidian
```

If you're still having issues with Obsidian launching, then you may have to start with a clean Obsidian data directory:

```
$ flatpak kill md.obsidian.Obsidian
$ mv ~/.var/app/md.obsidian.Obsidian ~/.var/app/md.obsidian.Obsidian.bak
$ flatpak run md.obsidian.Obsidian
```

**Comment by irm-codebase** [comment] 2024-02-18 17:07
Add me to the pile of complaints :')

Same issue in Fedora 39
![image](https://github.com/flathub/md.obsidian.Obsidian/assets/72193617/1eac2d25-c601-409f-a9fb-70e89a0f8865)

Clicking on "OK" several times works, but the connection to some plugins is botched (like Zotero).

**Comment by joshua-stone** [comment] 2024-02-18 17:08
@irm-codebase Please update as such: https://github.com/flathub/md.obsidian.Obsidian/issues/297#issuecomment-1951387475

**Comment by irm-codebase** [comment] 2024-02-18 17:09
> @irm-codebase Please update as such: [#297 (comment)](https://github.com/flathub/md.obsidian.Obsidian/issues/297#issuecomment-1951387475)

Just did, in fact! The problem is fixed on my side :)
Thank you for being so quick with the hotfix.

**Comment by lautome** [comment] 2024-02-18 17:40
> @irm-codebase Please update as such: [#297 (comment)](https://github.com/flathub/md.obsidian.Obsidian/issues/297#issuecomment-1951387475)

Excellent! Many thanks.

**Comment by IronLllama** [comment] 2024-02-18 20:28
Fixed here as well, thank you for such a quick fix - and on a Sunday too.

**Comment by coritanic** [comment] 2024-02-19 03:03
> Thanks it works for now but if I update I get this

`sudo flatpak mask md.obsidian.Obsidian` would pin the version and solve it.

**Comment by joshua-stone** [comment] 2024-02-19 03:15
Glad to hear that the hotfix worked! I think I can mark this issue as fixed.

**Closed by joshua-stone** 2024-02-19 03:15 UTC
Labels: bug

**Comment by vetricodes** [comment] 2024-02-19 04:03
fixed tysm C:

**Comment by blacklightpy** [comment] 2024-03-22 11:32
It's still there, on version 1.5.11.

![image](https://github.com/flathub/md.obsidian.Obsidian/assets/28739146/af644047-78ab-4a22-8c40-ed72476f656a)

**Comment by joshua-stone** [comment] 2024-03-22 13:27
@blacklightpy What version of Obsidian is shown when running `flatpak info md.obsidian.Obsidian`?

```
$ flatpak info md.obsidian.Obsidian

Obsidian - Markdown-based knowledge base

          ID: md.obsidian.Obsidian
         Ref: app/md.obsidian.Obsidian/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 1.5.11
     License: LicenseRef-proprietary=https://obsidian.md/eula
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 625.6 MB
     Runtime: org.freedesktop.Platform/x86_64/23.08
         Sdk: org.freedesktop.Sdk/x86_64/23.08

      Commit: 45aca5bfa83d1283e2b75ff7e9c394ea46697eb5eb48703b774f48fca4242c9a
      Parent: d3ec0e634d008391e743163ed233f25a2c92ecf8115c0d5147ffabf166ec91be
     Subject: Update 2 modules (d658668b)
        Date: 2024-03-20 19:20:36 +0000
```

Do you have an asar included in the Obsidian data directory?

```
$ find ~/.var/app/md.obsidian.Obsidian -name '*.asar'
```

You may have to remove it.

**Comment by blacklightpy** [comment] 2024-03-22 13:48
@joshua-stone
It was 1.5.13, now I downgraded to 1.5.3 as per the replies above. Let me see upgrading again.

**Comment by blacklightpy** [comment] 2024-03-22 13:51
Indeed there is a 1.5.11 asar. Lemme try removing and upgrading.

**Comment by joshua-stone** [comment] 2024-03-22 14:19
Alternatively, you can move the Obsidian folder to force a clean config folder:

```
$ flatpak kill md.obsidian.Obsidian
$ mv ~/.var/app/md.obsidian.Obsidian ~/.var/app/md.obsidian.Obsidian.bak
$ flatpak update md.obsidian.Obsidian
$ flatpak run md.obsidian.Obsidian
```

**Comment by blacklightpy** [comment] 2024-03-22 14:34
For now, it seems to be working, I'll report if that changes.

**Comment by blacklightpy** [comment] 2024-03-22 15:08
Oh no it looks like it's broken again. I'll try using a fresh setup.

**Comment by blacklightpy** [comment] 2024-03-22 15:18
One more thing to mention is that I'm using musl libc, on Void Linux distribution.

Electron isn't officially supported in musl, as chromium could only be supported after applying a bunch of patches. When I built an app from scratch with minimal patches, it showed the same errors I saw here on the terminal side. The dialog box is the same error as shown here.

So this maybe related to the fact that I'm running musl for some reason, but again, Flatpak is supposed to be immune to that.

**Comment by blacklightpy** [comment] 2024-03-22 16:11
No use, it's still showing the same error.

**Comment by blacklightpy** [comment] 2024-04-07 14:24
I noticed that this error did not occur when I was using KDE Plasma (for about 200 hours). It returned when I switched to Hyprland (within 30 min as usual). What could be missing??

**Comment by moridin-bin** [comment] 2024-04-16 05:12
@blacklightpy I have the same and similar errors on both Obsidian and Discord. I thought it was only Discord at first until I installed Obsidian a couple days ago and now am getting the errors but this time in relation to Obsidian, Discord isn't even open. I'm also running Hyprland. They're both Electron apps, unsure if that's relevant or if the issue is related to Hyprland/something missing from a Hyprland setup.
