### ISSUE TITLE
Write Error - Cannot Save File

### ISSUE THREAD

**Issue by valiantgenomics** [flathub/md.obsidian.Obsidian#203] opened 2023-09-13 22:31 UTC
### Description

First, thanks a ton for creating & maintaining the flatpak version of Obsidian. You have my eternal gratitude!

There seems to be some sort of permissions issue with the flatpak version, though.

When I add a spreadsheet to my Obsidian vault, and open the spreadsheet from within Obsidian, I cannot save any of the changes I make:

![Write error](https://github.com/flathub/md.obsidian.Obsidian/assets/111633318/cb9e3390-edfc-448e-abfb-d2a19dd06a91)

If I open the same spreadsheet outside of Obsidian, I can save it without any problems.

This is a LibreOffice spreadsheet. And the flatpak version seems to be prohibiting the 'saving' of the file somehow, because the .deb version of Obsidian doesn't have this problem.

I did try to allow it via Flatseal, but nothing worked. 

For example, I tried adding the Obsidian Vault directory in the Filesystem menu within Flatseal, which I thought would allow the Obsidian flatpak to maybe access these files, but it didn't work.

I also did a hail marry, and enabled EVERYTHING in Flatseal, all the permissions for both the Obsidian flatpak and the LibreOffice flatpak. Again, it didn't work.

Any ideas on how to tweak the flatpak, so it allows saving the edited files?

### System Information

```bash session
OS: Pop!_OS 22.04 LTS x86_64 
Kernel: 6.2.6-76060206-generic 
Shell: bash 5.1.16 
DE: GNOME 42.5 
WM: Mutter
```

### Sandbox Permissions

```bash session
flatpak info --show-permissions md.obsidian.Obsidian
[Context]
shared=network;ipc;
sockets=x11;wayland;pulseaudio;ssh-auth;
devices=dri;
filesystems=home;/media;/mnt;/run/media;xdg-run/app/com.discordapp.Discord:create;
persistent=~/.ssh;

[Session Bus Policy]
org.freedesktop.portal.Fcitx=talk

[Environment]
SSH_ASKPASS=/app/libexec/openssh/ssh-askpass
OBSIDIAN_ENABLE_AUTOSCROLL=0
PATH=/usr/bin:/app/bin:/app/texlive/bin:/app/texlive/bin/x86_64-linux:/app/texlive/bin/aarch64-linux
OBSIDIAN_DISABLE_GPU=0
GH_PATH=gh
OBSIDIAN_USE_WAYLAND=0
XCURSOR_PATH=/run/host/user-share/icons:/run/host/share/icons
OBSIDIAN_DISABLE_GPU_SANDBOX=0

Please keep in mind that I did reset the permissions after doing the hail marry and enabled ALL of them in Flatseal which didn't work, as stated above. So this log is after the permissions were reset back to default.
```

### Logs

```bash session
flatpak run md.obsidian.Obsidian
Debug: Will run Obsidian with the following arguments: 
Debug: Additionally, user gave: 
[13 zypak-helper] Wait found events, but sd-event found none
[13:0913/232916.429707:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
2023-09-13 22:29:16 Loading main app package /app/resources/obsidian.asar
Updates disabled.
LaunchProcess: failed to execvp:
xdg-settings
Gtk-Message: 23:29:16.614: Failed to load module "canberra-gtk-module"
Gtk-Message: 23:29:16.615: Failed to load module "canberra-gtk-module"
[13:0913/232916.640731:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
[13:0913/232916.640813:ERROR:bus.cc(399)] Failed to connect to the bus: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
```

**Comment by joshua-stone** [comment] 2023-09-14 02:19
This appears to be related to a LibreOffice bug:

https://github.com/flathub/org.libreoffice.LibreOffice/issues/203

To reproduce, first set the following option in LibreOffice:

```
Tools → Options → Advanced → Button: Open Expert Configuration → UseLocking → false
```

Then create a spreadsheet in LibreOffice and close it.

Finally, try to open that spreadsheet using xdg-open inside flatpak:

```
$ flatpak run --command=xdg-open --filesystem=home org.freedesktop.Platform//22.08 ~/path/to/test-document.ods
```

**Comment by joshua-stone** [comment] 2023-09-14 02:38
I've left a comment in the LO bug report. Marking this as closed since it doesn't appear to be caused by the Obsidian flatpak.

**Closed by joshua-stone** 2023-09-14 02:38 UTC
Labels: bug
